# 清华大学源
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
# 私有源
source 'https://github.com/kaibuleite/xSpecs.git'

use_frameworks!

platform :ios, '9.0'

target 'xPicker_Example' do
  pod 'xPicker', :path => '../'

  target 'xPicker_Tests' do
    inherit! :search_paths

    
  end
end
